[package]
name = "stake_neuron_from_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stake_neuron_from_cli"
path = "src/main.rs"

[dependencies]
ic-agent = "0.35"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
