[package]
name = "kongswap_adaptor"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
name = "kongswap_adaptor"
path = "src/lib.rs"

[[bin]]
name = "kongswap-adaptor-canister"
path = "src/canister.rs"

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-stable-structures = { workspace = true }
lazy_static = "1.5.0"
serde = { workspace = true }
maplit = "1.0.2"
itertools = "0.14.0"
thiserror = "2.0.12"
ic-canister-log = "0.2.0"
icrc-ledger-types.workspace = true
serde_json = "1.0.140"
pretty_assertions = "1.4.1"
derivative = "2.2"

[dev-dependencies]
pocket-ic.workspace = true
ic-management-canister-types.workspace = true
candid_parser = "0.1.2"
sha2 = "0.10.9"
tokio = { version = "1.45.1", features = ["test-util", "macros"] }
mockall = "0.11"
